fn main() {
    android_16kb_page_alignment();
    tauri_build::build();
}

/// Force 16 KB ELF `LOAD` alignment on every Android artifact (#4425).
///
/// Android 15+ devices can boot with a **16 KB page size**. On those the
/// dynamic linker refuses to map a shared library whose `PT_LOAD` segments
/// are aligned to 4 KB, and the app does not start — there is no degraded
/// mode. Google Play additionally requires 16 KB support for apps targeting
/// Android 15+.
///
/// NDK r27 emits 16 KB-aligned output for the build systems it owns (its
/// CMake/ndk-build toolchain files add this same flag), but a Rust
/// cross-compile drives `clang` through *cargo's* own link invocation and
/// inherits none of that. The shipped 0.9.9 APK was therefore 4 KB-aligned:
///
/// ```text
/// $ readelf -lW lib/arm64-v8a/libagaric_lib.so | awk '$1=="LOAD"{print $NF}' | sort -u
/// 0x1000
/// ```
///
/// # Why this lives in `build.rs`
///
/// The obvious home is `[target.aarch64-linux-android] rustflags`, but
/// `.cargo/config.toml` is **gitignored** in this repo (`.gitignore` pins the
/// bare `config.toml` name, which matches at any depth) — `scripts/setup.sh`
/// writes a per-machine one for the fast linker, and only the `.example` is
/// tracked. A fix parked there would work on one developer's machine and
/// never reach CI or the release job. The other candidate,
/// `gen/android/app/build.gradle.kts`, is regenerated by
/// `cargo tauri android init` on every CI run (only six files under
/// `gen/android/` are tracked, and that is not one of them).
///
/// `build.rs` is tracked, is read by *every* invocation that links the
/// Android `cdylib` — local `cargo tauri android build`, `ci.yml`'s
/// `android-build`, and `release.yml`'s `android-build-and-release` alike —
/// and needs no workflow-level `RUSTFLAGS` export to stay in force.
///
/// # Scope
///
/// Gated on `CARGO_CFG_TARGET_OS == "android"`, so it covers both Android
/// targets we build (`aarch64-linux-android` in the release, plus the
/// `x86_64-linux-android` emulator build in `ci.yml`) without enumerating
/// triples, and is inert for every desktop target. `cargo::rustc-link-arg`
/// applies to the package's binaries, examples, tests **and cdylib** — which
/// is exactly `libagaric_lib.so`, the file Android loads.
///
/// Verified with `readelf -lW … | awk '$1=="LOAD"{print $NF}' | sort -u`
/// printing `0x4000`; `scripts/check-android-so-alignment.mjs` asserts it in
/// CI so this cannot regress silently again.
fn android_16kb_page_alignment() {
    // Cargo re-runs this script when it changes; make that explicit, since
    // emitting any `cargo::` instruction suppresses the default heuristic.
    println!("cargo::rerun-if-changed=build.rs");

    if std::env::var("CARGO_CFG_TARGET_OS").as_deref() == Ok("android") {
        println!("cargo::rustc-link-arg=-Wl,-z,max-page-size=16384");
    }
}
