// @ts-nocheck

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Tauri command: create a new block. Delegates to [`create_block_inner`].
 */
async createBlock(blockType: string, content: string, parentId: string | null, position: number | null) : Promise<Result<BlockResponse, { kind: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_block", { blockType, content, parentId, position }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: edit a block's content. Delegates to [`edit_block_inner`].
 */
async editBlock(blockId: string, toText: string) : Promise<Result<BlockResponse, { kind: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("edit_block", { blockId, toText }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: soft-delete a block and descendants. Delegates to [`delete_block_inner`].
 */
async deleteBlock(blockId: string) : Promise<Result<DeleteResponse, { kind: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_block", { blockId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: restore a soft-deleted block. Delegates to [`restore_block_inner`].
 */
async restoreBlock(blockId: string, deletedAtRef: string) : Promise<Result<RestoreResponse, { kind: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("restore_block", { blockId, deletedAtRef }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: permanently purge a soft-deleted block. Delegates to [`purge_block_inner`].
 */
async purgeBlock(blockId: string) : Promise<Result<PurgeResponse, { kind: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("purge_block", { blockId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: move a block to a new parent at a given position. Delegates to [`move_block_inner`].
 */
async moveBlock(blockId: string, newParentId: string | null, newPosition: number) : Promise<Result<MoveResponse, { kind: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("move_block", { blockId, newParentId, newPosition }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: list blocks with filtering and pagination. Delegates to [`list_blocks_inner`].
 */
async listBlocks(parentId: string | null, blockType: string | null, tagId: string | null, showDeleted: boolean | null, agendaDate: string | null, cursor: string | null, limit: number | null) : Promise<Result<PageResponse<BlockRow>, { kind: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_blocks", { parentId, blockType, tagId, showDeleted, agendaDate, cursor, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: fetch a single block by ID. Delegates to [`get_block_inner`].
 */
async getBlock(blockId: string) : Promise<Result<BlockRow, { kind: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_block", { blockId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: add a tag to a block. Delegates to [`add_tag_inner`].
 */
async addTag(blockId: string, tagId: string) : Promise<Result<TagResponse, { kind: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_tag", { blockId, tagId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: remove a tag from a block. Delegates to [`remove_tag_inner`].
 */
async removeTag(blockId: string, tagId: string) : Promise<Result<TagResponse, { kind: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_tag", { blockId, tagId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: list backlinks for a block. Delegates to [`get_backlinks_inner`].
 */
async getBacklinks(blockId: string, cursor: string | null, limit: number | null) : Promise<Result<PageResponse<BlockRow>, { kind: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_backlinks", { blockId, cursor, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: list op-log history for a block. Delegates to [`get_block_history_inner`].
 */
async getBlockHistory(blockId: string, cursor: string | null, limit: number | null) : Promise<Result<PageResponse<HistoryEntry>, { kind: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_block_history", { blockId, cursor, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: list conflict-copy blocks. Delegates to [`get_conflicts_inner`].
 */
async getConflicts(cursor: string | null, limit: number | null) : Promise<Result<PageResponse<BlockRow>, { kind: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_conflicts", { cursor, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: get materializer queue status. Delegates to [`get_status_inner`].
 */
async getStatus() : Promise<Result<StatusInfo, { kind: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: full-text search across blocks. Delegates to [`search_blocks_inner`].
 */
async searchBlocks(query: string, cursor: string | null, limit: number | null) : Promise<Result<PageResponse<BlockRow>, { kind: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("search_blocks", { query, cursor, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: query blocks by boolean tag expression. Delegates to [`query_by_tags_inner`].
 */
async queryByTags(tagIds: string[], prefixes: string[], mode: string, cursor: string | null, limit: number | null) : Promise<Result<PageResponse<BlockRow>, { kind: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("query_by_tags", { tagIds, prefixes, mode, cursor, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: list tags matching a name prefix. Delegates to [`list_tags_by_prefix_inner`].
 */
async listTagsByPrefix(prefix: string) : Promise<Result<TagCacheRow[], { kind: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_tags_by_prefix", { prefix }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: list tag IDs for a block. Delegates to [`list_tags_for_block_inner`].
 */
async listTagsForBlock(blockId: string) : Promise<Result<string[], { kind: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_tags_for_block", { blockId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: set (upsert) a property on a block. Delegates to [`set_property_inner`].
 */
async setProperty(blockId: string, key: string, valueText: string | null, valueNum: number | null, valueDate: string | null, valueRef: string | null) : Promise<Result<BlockResponse, { kind: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_property", { blockId, key, valueText, valueNum, valueDate, valueRef }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: delete a property from a block. Delegates to [`delete_property_inner`].
 */
async deleteProperty(blockId: string, key: string) : Promise<Result<null, { kind: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_property", { blockId, key }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: get all properties for a block. Delegates to [`get_properties_inner`].
 */
async getProperties(blockId: string) : Promise<Result<PropertyRow[], { kind: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_properties", { blockId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type BlockResponse = { id: string; block_type: string; content: string | null; parent_id: string | null; position: number | null; deleted_at: string | null }
/**
 * Row returned by paginated block queries.
 */
export type BlockRow = { id: string; block_type: string; content: string | null; parent_id: string | null; position: number | null; deleted_at: string | null; archived_at: string | null; is_conflict: boolean }
export type DeleteResponse = { block_id: string; deleted_at: string; descendants_affected: number }
/**
 * Row returned by block history queries (op_log entries for a block).
 */
export type HistoryEntry = { device_id: string; seq: number; op_type: string; payload: string; created_at: string }
export type MoveResponse = { block_id: string; new_parent_id: string | null; new_position: number }
/**
 * Paginated response.
 *
 * `total_count` is intentionally omitted — see module docs.
 */
export type PageResponse<T> = { items: T[]; next_cursor: string | null; has_more: boolean }
export type PropertyRow = { key: string; value_text: string | null; value_num: number | null; value_date: string | null; value_ref: string | null }
export type PurgeResponse = { block_id: string; purged_count: number }
export type RestoreResponse = { block_id: string; restored_count: number }
/**
 * Serializable status snapshot of the materializer queues.
 *
 * Built from [`QueueMetrics`] (atomic counters) and channel capacity info.
 * Exposed by the `get_status` command.
 */
export type StatusInfo = { foreground_queue_depth: number; background_queue_depth: number; total_ops_dispatched: number; total_background_dispatched: number; fg_high_water: number; bg_high_water: number; fg_errors: number; bg_errors: number; fg_panics: number; bg_panics: number }
/**
 * Row from `tags_cache`, used by `list_tags_by_prefix`.
 */
export type TagCacheRow = { tag_id: string; name: string; usage_count: number; updated_at: string }
export type TagResponse = { block_id: string; tag_id: string }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
