// @ts-nocheck

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Tauri command: create a new block. Delegates to [`create_block_inner`].
 */
async createBlock(blockType: string, content: string, parentId: string | null, position: number | null) : Promise<Result<BlockRow, { kind: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_block", { blockType, content, parentId, position }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: edit a block's content. Delegates to [`edit_block_inner`].
 */
async editBlock(blockId: string, toText: string) : Promise<Result<BlockRow, { kind: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("edit_block", { blockId, toText }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: soft-delete a block and descendants. Delegates to [`delete_block_inner`].
 */
async deleteBlock(blockId: string) : Promise<Result<DeleteResponse, { kind: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_block", { blockId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: restore a soft-deleted block. Delegates to [`restore_block_inner`].
 */
async restoreBlock(blockId: string, deletedAtRef: string) : Promise<Result<RestoreResponse, { kind: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("restore_block", { blockId, deletedAtRef }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: permanently purge a soft-deleted block. Delegates to [`purge_block_inner`].
 */
async purgeBlock(blockId: string) : Promise<Result<PurgeResponse, { kind: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("purge_block", { blockId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: move a block to a new parent at a given position. Delegates to [`move_block_inner`].
 */
async moveBlock(blockId: string, newParentId: string | null, newPosition: number) : Promise<Result<MoveResponse, { kind: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("move_block", { blockId, newParentId, newPosition }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: list blocks with filtering and pagination. Delegates to [`list_blocks_inner`].
 */
async listBlocks(parentId: string | null, blockType: string | null, tagId: string | null, showDeleted: boolean | null, agendaDate: string | null, agendaDateRange: DateRange | null, agendaSource: string | null, cursor: string | null, limit: number | null) : Promise<Result<PageResponse<BlockRow>, { kind: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_blocks", { parentId, blockType, tagId, showDeleted, agendaDate, agendaDateRange, agendaSource, cursor, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: fetch a single block by ID. Delegates to [`get_block_inner`].
 */
async getBlock(blockId: string) : Promise<Result<BlockRow, { kind: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_block", { blockId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: batch-resolve block metadata. Delegates to [`batch_resolve_inner`].
 */
async batchResolve(ids: string[]) : Promise<Result<ResolvedBlock[], { kind: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("batch_resolve", { ids }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: add a tag to a block. Delegates to [`add_tag_inner`].
 */
async addTag(blockId: string, tagId: string) : Promise<Result<TagResponse, { kind: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_tag", { blockId, tagId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: remove a tag from a block. Delegates to [`remove_tag_inner`].
 */
async removeTag(blockId: string, tagId: string) : Promise<Result<TagResponse, { kind: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_tag", { blockId, tagId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: list backlinks for a block. Delegates to [`get_backlinks_inner`].
 */
async getBacklinks(blockId: string, cursor: string | null, limit: number | null) : Promise<Result<PageResponse<BlockRow>, { kind: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_backlinks", { blockId, cursor, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: list op-log history for a block. Delegates to [`get_block_history_inner`].
 */
async getBlockHistory(blockId: string, cursor: string | null, limit: number | null) : Promise<Result<PageResponse<HistoryEntry>, { kind: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_block_history", { blockId, cursor, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: list conflict-copy blocks. Delegates to [`get_conflicts_inner`].
 */
async getConflicts(cursor: string | null, limit: number | null) : Promise<Result<PageResponse<BlockRow>, { kind: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_conflicts", { cursor, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: get materializer queue status. Delegates to [`get_status_inner`].
 */
async getStatus() : Promise<Result<StatusInfo, { kind: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: full-text search across blocks. Delegates to [`search_blocks_inner`].
 */
async searchBlocks(query: string, cursor: string | null, limit: number | null) : Promise<Result<PageResponse<BlockRow>, { kind: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("search_blocks", { query, cursor, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: query blocks by boolean tag expression. Delegates to [`query_by_tags_inner`].
 */
async queryByTags(tagIds: string[], prefixes: string[], mode: string, includeInherited: boolean | null, cursor: string | null, limit: number | null) : Promise<Result<PageResponse<BlockRow>, { kind: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("query_by_tags", { tagIds, prefixes, mode, includeInherited, cursor, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: query blocks by property key/value. Delegates to [`query_by_property_inner`].
 */
async queryByProperty(key: string, valueText: string | null, valueDate: string | null, operator: string | null, cursor: string | null, limit: number | null) : Promise<Result<PageResponse<BlockRow>, { kind: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("query_by_property", { key, valueText, valueDate, operator, cursor, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: list tags matching a name prefix. Delegates to [`list_tags_by_prefix_inner`].
 */
async listTagsByPrefix(prefix: string, limit: number | null) : Promise<Result<TagCacheRow[], { kind: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_tags_by_prefix", { prefix, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: list tag IDs for a block. Delegates to [`list_tags_for_block_inner`].
 */
async listTagsForBlock(blockId: string) : Promise<Result<string[], { kind: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_tags_for_block", { blockId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: set (upsert) a property on a block. Delegates to [`set_property_inner`].
 */
async setProperty(blockId: string, key: string, valueText: string | null, valueNum: number | null, valueDate: string | null, valueRef: string | null) : Promise<Result<BlockRow, { kind: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_property", { blockId, key, valueText, valueNum, valueDate, valueRef }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: set todo state on a block. Delegates to [`set_todo_state_inner`].
 */
async setTodoState(blockId: string, state: string | null) : Promise<Result<BlockRow, { kind: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_todo_state", { blockId, state }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: set priority on a block. Delegates to [`set_priority_inner`].
 */
async setPriority(blockId: string, level: string | null) : Promise<Result<BlockRow, { kind: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_priority", { blockId, level }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: set due date on a block. Delegates to [`set_due_date_inner`].
 */
async setDueDate(blockId: string, date: string | null) : Promise<Result<BlockRow, { kind: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_due_date", { blockId, date }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: set scheduled date on a block. Delegates to [`set_scheduled_date_inner`].
 */
async setScheduledDate(blockId: string, date: string | null) : Promise<Result<BlockRow, { kind: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_scheduled_date", { blockId, date }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: delete a property from a block. Delegates to [`delete_property_inner`].
 */
async deleteProperty(blockId: string, key: string) : Promise<Result<null, { kind: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_property", { blockId, key }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: get all properties for a block. Delegates to [`get_properties_inner`].
 */
async getProperties(blockId: string) : Promise<Result<PropertyRow[], { kind: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_properties", { blockId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: batch-fetch properties. Delegates to [`get_batch_properties_inner`].
 */
async getBatchProperties(blockIds: string[]) : Promise<Result<Partial<{ [key in string]: PropertyRow[] }>, { kind: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_batch_properties", { blockIds }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: list page history. Delegates to [`list_page_history_inner`].
 */
async listPageHistory(pageId: string, opTypeFilter: string | null, cursor: string | null, limit: number | null) : Promise<Result<PageResponse<HistoryEntry>, { kind: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_page_history", { pageId, opTypeFilter, cursor, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: batch revert ops. Delegates to [`revert_ops_inner`].
 */
async revertOps(ops: OpRef[]) : Promise<Result<UndoResult[], { kind: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("revert_ops", { ops }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: undo page op. Delegates to [`undo_page_op_inner`].
 */
async undoPageOp(pageId: string, undoDepth: number) : Promise<Result<UndoResult, { kind: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("undo_page_op", { pageId, undoDepth }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: redo page op. Delegates to [`redo_page_op_inner`].
 */
async redoPageOp(undoDeviceId: string, undoSeq: number) : Promise<Result<UndoResult, { kind: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("redo_page_op", { undoDeviceId, undoSeq }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: compute word-level diff for an edit_block history entry.
 * Delegates to [`compute_edit_diff_inner`].
 */
async computeEditDiff(deviceId: string, seq: number) : Promise<Result<DiffSpan[] | null, { kind: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("compute_edit_diff", { deviceId, seq }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: filtered backlink query. Delegates to [`query_backlinks_filtered_inner`].
 */
async queryBacklinksFiltered(blockId: string, filters: BacklinkFilter[] | null, sort: BacklinkSort | null, cursor: string | null, limit: number | null) : Promise<Result<BacklinkQueryResponse, { kind: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("query_backlinks_filtered", { blockId, filters, sort, cursor, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: grouped backlink query. Delegates to [`list_backlinks_grouped_inner`].
 */
async listBacklinksGrouped(blockId: string, filters: BacklinkFilter[] | null, sort: BacklinkSort | null, cursor: string | null, limit: number | null) : Promise<Result<GroupedBacklinkResponse, { kind: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_backlinks_grouped", { blockId, filters, sort, cursor, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: unlinked references query. Delegates to [`list_unlinked_references_inner`].
 */
async listUnlinkedReferences(pageId: string, cursor: string | null, limit: number | null) : Promise<Result<GroupedBacklinkResponse, { kind: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_unlinked_references", { pageId, cursor, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: list distinct property keys. Delegates to [`list_property_keys_inner`].
 */
async listPropertyKeys() : Promise<Result<string[], { kind: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_property_keys") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: create a property definition. Delegates to [`create_property_def_inner`].
 */
async createPropertyDef(key: string, valueType: string, options: string | null) : Promise<Result<PropertyDefinition, { kind: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_property_def", { key, valueType, options }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: list all property definitions. Delegates to [`list_property_defs_inner`].
 */
async listPropertyDefs() : Promise<Result<PropertyDefinition[], { kind: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_property_defs") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: update options for a select-type definition. Delegates to [`update_property_def_options_inner`].
 */
async updatePropertyDefOptions(key: string, options: string) : Promise<Result<PropertyDefinition, { kind: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_property_def_options", { key, options }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: delete a property definition. Delegates to [`delete_property_def_inner`].
 */
async deletePropertyDef(key: string) : Promise<Result<null, { kind: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_property_def", { key }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: list all sync peers. Delegates to [`list_peer_refs_inner`].
 */
async listPeerRefs() : Promise<Result<PeerRef[], { kind: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_peer_refs") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: get a single sync peer by ID. Delegates to [`get_peer_ref_inner`].
 */
async getPeerRef(peerId: string) : Promise<Result<PeerRef | null, { kind: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_peer_ref", { peerId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: delete (unpair) a sync peer. Delegates to [`delete_peer_ref_inner`].
 */
async deletePeerRef(peerId: string) : Promise<Result<null, { kind: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_peer_ref", { peerId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updatePeerName(peerId: string, deviceName: string | null) : Promise<Result<null, { kind: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_peer_name", { peerId, deviceName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: set a peer's last-known network address for direct connection.
 */
async setPeerAddress(peerId: string, address: string) : Promise<Result<null, { kind: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_peer_address", { peerId, address }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: return the local device's persistent UUID.
 */
async getDeviceId() : Promise<Result<string, { kind: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_device_id") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: start a new pairing session.
 * Generates a passphrase + QR SVG and stores the session in managed state.
 */
async startPairing() : Promise<Result<PairingInfo, { kind: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_pairing") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: confirm pairing with a remote device.
 * Stores the peer ref in the database and clears the pairing session.
 */
async confirmPairing(passphrase: string, remoteDeviceId: string) : Promise<Result<null, { kind: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("confirm_pairing", { passphrase, remoteDeviceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: cancel an in-progress pairing session.
 */
async cancelPairing() : Promise<Result<null, { kind: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_pairing") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: start sync with a remote peer.
 * Checks backoff (#278), acquires the per-peer lock, and returns session info.
 */
async startSync(peerId: string) : Promise<Result<SyncSessionInfo, { kind: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_sync", { peerId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: cancel an active sync session.
 */
async cancelSync() : Promise<Result<null, { kind: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_sync") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: batch-count agenda items per date. Delegates to [`count_agenda_batch_inner`].
 */
async countAgendaBatch(dates: string[]) : Promise<Result<Partial<{ [key in string]: number }>, { kind: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("count_agenda_batch", { dates }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: batch-count agenda items per (date, source). Delegates to [`count_agenda_batch_by_source_inner`].
 */
async countAgendaBatchBySource(dates: string[]) : Promise<Result<Partial<{ [key in string]: Partial<{ [key in string]: number }> }>, { kind: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("count_agenda_batch_by_source", { dates }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: batch-count backlinks per target page. Delegates to [`count_backlinks_batch_inner`].
 */
async countBacklinksBatch(pageIds: string[]) : Promise<Result<Partial<{ [key in string]: number }>, { kind: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("count_backlinks_batch", { pageIds }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: set page aliases. Delegates to [`set_page_aliases_inner`].
 */
async setPageAliases(pageId: string, aliases: string[]) : Promise<Result<string[], { kind: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_page_aliases", { pageId, aliases }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: get page aliases. Delegates to [`get_page_aliases_inner`].
 */
async getPageAliases(pageId: string) : Promise<Result<string[], { kind: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_page_aliases", { pageId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: resolve a page by alias. Delegates to [`resolve_page_by_alias_inner`].
 */
async resolvePageByAlias(alias: string) : Promise<Result<[string, string | null] | null, { kind: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resolve_page_by_alias", { alias }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: export a page as Markdown. Delegates to [`export_page_markdown_inner`].
 */
async exportPageMarkdown(pageId: string) : Promise<Result<string, { kind: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_page_markdown", { pageId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: list projected future occurrences of repeating tasks.
 * Delegates to [`list_projected_agenda_inner`].
 */
async listProjectedAgenda(startDate: string, endDate: string, limit: number | null) : Promise<Result<ProjectedAgendaEntry[], { kind: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_projected_agenda", { startDate, endDate, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: import a Logseq-style markdown file as a page with
 * block hierarchy. Delegates to [`import_markdown_inner`].
 */
async importMarkdown(content: string, filename: string | null) : Promise<Result<ImportResult, { kind: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_markdown", { content, filename }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: add an attachment to a block. Delegates to [`add_attachment_inner`].
 */
async addAttachment(blockId: string, filename: string, mimeType: string, sizeBytes: number, fsPath: string) : Promise<Result<AttachmentRow, { kind: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_attachment", { blockId, filename, mimeType, sizeBytes, fsPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: delete an attachment. Delegates to [`delete_attachment_inner`].
 */
async deleteAttachment(attachmentId: string) : Promise<Result<null, { kind: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_attachment", { attachmentId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: list attachments for a block. Delegates to [`list_attachments_inner`].
 */
async listAttachments(blockId: string) : Promise<Result<AttachmentRow[], { kind: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_attachments", { blockId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: save a draft for a block. Delegates to [`draft::save_draft`].
 */
async saveDraft(blockId: string, content: string) : Promise<Result<null, { kind: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_draft", { blockId, content }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: flush a draft (write edit_block op + delete draft row).
 * Delegates to [`flush_draft_inner`].
 */
async flushDraft(blockId: string) : Promise<Result<null, { kind: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("flush_draft", { blockId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: delete a draft for a block. Delegates to [`draft::delete_draft`].
 */
async deleteDraft(blockId: string) : Promise<Result<null, { kind: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_draft", { blockId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: list all drafts. Delegates to [`draft::get_all_drafts`].
 */
async listDrafts() : Promise<Result<Draft[], { kind: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_drafts") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Log a frontend message to the backend's daily-rolling log file.
 * Fire-and-forget — the frontend never awaits this.
 */
async logFrontend(level: string, module: string, message: string, stack: string | null, context: string | null) : Promise<Result<null, { kind: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("log_frontend", { level, module, message, stack, context }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Return the path to the logs directory.
 */
async getLogDir() : Promise<Result<string, { kind: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_log_dir") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: return op log compaction statistics for the UI.
 */
async getCompactionStatus() : Promise<Result<CompactionStatus, { kind: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_compaction_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: trigger op log compaction.
 *
 * The frontend is responsible for confirming with the user before calling
 * this command. `retention_days` controls how far back ops are retained.
 */
async compactOpLogCmd(retentionDays: number) : Promise<Result<CompactionResult, { kind: string; message: string }>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("compact_op_log_cmd", { retentionDays }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AttachmentRow = { id: string; block_id: string; mime_type: string; filename: string; size_bytes: number; fs_path: string; created_at: string }
/**
 * Tagged union of filter predicates for backlink queries.
 *
 * Filters are combined with AND semantics at the top level.
 * Use `And`/`Or`/`Not` variants for compound boolean logic.
 */
export type BacklinkFilter = { type: "PropertyText"; key: string; op: CompareOp; value: string } | { type: "PropertyNum"; key: string; op: CompareOp; value: number } | { type: "PropertyDate"; key: string; op: CompareOp; value: string } | { type: "PropertyIsSet"; key: string } | { type: "PropertyIsEmpty"; key: string } |
/**
 * Filter blocks by todo_state column (direct, no block_properties join).
 */
{ type: "TodoState"; state: string } |
/**
 * Filter blocks by priority column (direct, no block_properties join).
 */
{ type: "Priority"; level: string } |
/**
 * Filter blocks by due_date column with comparison operator.
 */
{ type: "DueDate"; op: CompareOp; value: string } | { type: "HasTag"; tag_id: string } | { type: "HasTagPrefix"; prefix: string } | { type: "Contains"; query: string } | { type: "CreatedInRange"; after: string | null; before: string | null } | { type: "BlockType"; block_type: string } |
/**
 * Filter by source page — include/exclude blocks based on their root page ancestor.
 */
{ type: "SourcePage"; included: string[]; excluded: string[] } | { type: "And"; filters: BacklinkFilter[] } | { type: "Or"; filters: BacklinkFilter[] } | { type: "Not"; filter: BacklinkFilter }
/**
 * A group of backlinks from the same source page.
 */
export type BacklinkGroup = { page_id: string; page_title: string | null; blocks: BlockRow[] }
/**
 * Response for a filtered backlink query, including total count.
 */
export type BacklinkQueryResponse = { items: BlockRow[]; next_cursor: string | null; has_more: boolean; total_count: number; filtered_count: number }
/**
 * Tagged union of sort modes for backlink queries.
 */
export type BacklinkSort = { type: "Created"; dir: SortDir } | { type: "PropertyText"; key: string; dir: SortDir } | { type: "PropertyNum"; key: string; dir: SortDir } | { type: "PropertyDate"; key: string; dir: SortDir }
/**
 * Row returned by paginated block queries.
 */
export type BlockRow = { id: string; block_type: string; content: string | null; parent_id: string | null; position: number | null; deleted_at: string | null; is_conflict: boolean; conflict_type: string | null; todo_state: string | null; priority: string | null; due_date: string | null; scheduled_date: string | null }
/**
 * Result of an op log compaction, returned by [`compact_op_log_cmd`].
 */
export type CompactionResult = { snapshot_id: string | null; ops_deleted: number }
/**
 * Statistics about the op log, returned by [`get_compaction_status`].
 */
export type CompactionStatus = { total_ops: number; oldest_op_date: string | null; eligible_ops: number; retention_days: number }
/**
 * Comparison operators for property filters.
 */
export type CompareOp = "Eq" | "Neq" | "Lt" | "Gt" | "Lte" | "Gte" | "Contains" | "StartsWith"
/**
 * A date range for agenda queries. Both fields must be in `YYYY-MM-DD` format.
 */
export type DateRange = { start: string; end: string }
export type DeleteResponse = { block_id: string; deleted_at: string; descendants_affected: number }
/**
 * A contiguous span of text with a diff tag.
 */
export type DiffSpan = { tag: DiffTag; value: string }
/**
 * Tag indicating what happened to a span of text.
 */
export type DiffTag = "Equal" | "Delete" | "Insert"
/**
 * A single draft row from `block_drafts`.
 */
export type Draft = { block_id: string; content: string; updated_at: string }
/**
 * Response for grouped backlink queries — backlinks organized by source page.
 */
export type GroupedBacklinkResponse = { groups: BacklinkGroup[]; next_cursor: string | null; has_more: boolean; total_count: number; filtered_count: number }
/**
 * Row returned by block history queries (op_log entries for a block).
 */
export type HistoryEntry = { device_id: string; seq: number; op_type: string; payload: string; created_at: string }
/**
 * Result of parsing a markdown file.
 */
export type ImportResult = { page_title: string; blocks_created: number; properties_set: number; warnings: string[] }
export type MoveResponse = { block_id: string; new_parent_id: string | null; new_position: number }
/**
 * Reference to a specific op in the log.
 */
export type OpRef = { device_id: string; seq: number }
/**
 * Paginated response.
 *
 * `total_count` is intentionally omitted — see module docs.
 */
export type PageResponse<T> = { items: T[]; next_cursor: string | null; has_more: boolean }
/**
 * Response payload returned by [`start_pairing`].
 */
export type PairingInfo = { passphrase: string; qr_svg: string; port: number }
/**
 * A row from the `peer_refs` table representing a remote sync peer.
 */
export type PeerRef = { peer_id: string; last_hash: string | null; last_sent_hash: string | null; synced_at: string | null; reset_count: number; last_reset_at: string | null;
/**
 * SHA-256 hex of the peer's TLS certificate, observed during pairing.
 * Used for certificate pinning on reconnection.
 */
cert_hash: string | null;
/**
 * Human-readable name/label for this peer (e.g. "Javier's Phone").
 */
device_name: string | null;
/**
 * Last known network address (host:port) for direct connection.
 * Updated after each successful sync. Used when mDNS is unavailable.
 */
last_address: string | null }
/**
 * A projected future occurrence of a repeating block.
 *
 * Not stored in the database — computed on-the-fly from repeat rules.
 */
export type ProjectedAgendaEntry = {
/**
 * The source block (real, materialized block).
 */
block: BlockRow;
/**
 * The projected date for this occurrence (YYYY-MM-DD).
 */
projected_date: string;
/**
 * Which date column was used as the base for projection.
 */
source: string }
/**
 * A property definition from the schema registry.
 */
export type PropertyDefinition = { key: string; value_type: string; options: string | null; created_at: string }
export type PropertyRow = { key: string; value_text: string | null; value_num: number | null; value_date: string | null; value_ref: string | null }
export type PurgeResponse = { block_id: string; purged_count: number }
/**
 * Lightweight metadata returned by [`batch_resolve_inner`].
 */
export type ResolvedBlock = { id: string;
/**
 * `content` column — page title, tag name, or content text (truncated).
 */
title: string | null; block_type: string; deleted: boolean }
export type RestoreResponse = { block_id: string; restored_count: number }
/**
 * Sort direction.
 */
export type SortDir = "Asc" | "Desc"
/**
 * Serializable status snapshot of the materializer queues.
 *
 * Built from [`QueueMetrics`] (atomic counters) and channel capacity info.
 * Exposed by the `get_status` command.
 */
export type StatusInfo = { foreground_queue_depth: number; background_queue_depth: number; total_ops_dispatched: number; total_background_dispatched: number; fg_high_water: number; bg_high_water: number; fg_errors: number; bg_errors: number; fg_panics: number; bg_panics: number }
/**
 * Response payload returned by [`start_sync`].
 */
export type SyncSessionInfo = { state: string; local_device_id: string; remote_device_id: string; ops_received: number; ops_sent: number }
/**
 * Row from `tags_cache`, used by `list_tags_by_prefix`.
 */
export type TagCacheRow = { tag_id: string; name: string; usage_count: number; updated_at: string }
export type TagResponse = { block_id: string; tag_id: string }
/**
 * Result of an undo or redo operation.
 */
export type UndoResult = {
/**
 * The op that was reversed (the original op for undo, the undo-op for redo).
 */
reversed_op: OpRef;
/**
 * The newly appended reverse op.
 */
new_op_ref: OpRef;
/**
 * The op_type of the newly appended op.
 */
new_op_type: string;
/**
 * Whether this was a redo (true) or undo (false).
 */
is_redo: boolean }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
