-- Issue #109 Phase 2: migrate `pages_cache.updated_at` from TEXT (RFC 3339)
-- to INTEGER milliseconds-since-UNIX-epoch (UTC), the canonical timestamp
-- encoding (Phase 1 / migrations/AGENTS.md; written via `crate::db::now_ms()`).
--
-- `pages_cache` is a derived, rebuildable cache. `updated_at` is
-- self-generated by the rebuild (`rebuild_pages_cache_impl` stamps
-- `crate::now_rfc3339()`), NOT sourced from any op's `created_at`, and is
-- never compared in a cross-table SQL predicate — so it is independent of the
-- `op_log.created_at` cluster. (The M-2 "preserve `updated_at` unless the
-- title changed" recency semantic compares the cache value only to itself.)
--
-- Rebuild recipe (precedent 0061/0062/0073). The table is already STRICT and
-- the FK `page_id REFERENCES blocks(id) ON DELETE CASCADE`, the
-- `inbound_link_count` / `child_block_count` columns (0069), and the
-- `idx_pages_cache_title_nocase` index (0068) are all preserved. Backfill
-- converts the RFC 3339 value via the `julianday`-based epoch-ms formula
-- (ms-precise).

CREATE TABLE _new_pages_cache (
    page_id    TEXT PRIMARY KEY NOT NULL REFERENCES blocks(id) ON DELETE CASCADE,
    title      TEXT NOT NULL,
    -- milliseconds since UNIX epoch (UTC); written via crate::db::now_ms()
    updated_at INTEGER NOT NULL CHECK (updated_at >= 0),
    inbound_link_count INTEGER NOT NULL DEFAULT 0,
    child_block_count  INTEGER NOT NULL DEFAULT 0
) STRICT;

INSERT INTO _new_pages_cache
    (page_id, title, updated_at, inbound_link_count, child_block_count)
    SELECT page_id, title,
           CAST(ROUND((julianday(updated_at) - 2440587.5) * 86400000.0) AS INTEGER),
           inbound_link_count, child_block_count
    FROM pages_cache;

DROP TABLE pages_cache;
ALTER TABLE _new_pages_cache RENAME TO pages_cache;

CREATE INDEX IF NOT EXISTS idx_pages_cache_title_nocase
    ON pages_cache(title COLLATE NOCASE);
