/**
 * KatexMath — renders LaTeX math via KaTeX (#1437).
 *
 * Lazy-loaded (this whole module, KaTeX itself, and KaTeX's CSS are pulled in
 * only when a math node is shown) so the ~250 kB KaTeX library stays OUT of the
 * editor/index chunk and off the first-paint critical path (#750). Mirrors the
 * MermaidDiagram lazy pattern.
 *
 * `katex.renderToString` is called with `throwOnError: false`, so invalid
 * LaTeX never throws — KaTeX renders the offending source inline in its error
 * colour. We additionally guard the call in a try/catch so an unexpected throw
 * degrades to the raw source rather than crashing the editor.
 */

// Importing the CSS here (not in a top-level entry) keeps it in the lazy chunk's
// asset graph so it loads alongside KaTeX, never on first paint.
import 'katex/dist/katex.min.css'
import katex from 'katex'
import { useMemo } from 'react'

export interface KatexMathProps {
  /** Raw LaTeX source. */
  latex: string
  /** Display (block) mode vs inline mode. */
  display?: boolean
}

export function KatexMath({ latex, display = false }: KatexMathProps): React.ReactElement {
  const html = useMemo(() => {
    try {
      return katex.renderToString(latex, {
        displayMode: display,
        // Never throw on invalid LaTeX — render the source in the error colour
        // so a typo shows an inline, readable error instead of crashing.
        throwOnError: false,
        // Visible, non-fatal error styling for invalid input.
        errorColor: '#cc0000',
      })
    } catch {
      // Defensive: KaTeX should not throw with throwOnError:false, but if it
      // ever does, degrade to the raw source rather than letting the editor
      // node view crash.
      return null
    }
  }, [latex, display])

  if (html === null) {
    return (
      <code className="katex-error-fallback text-alert-error-foreground" data-testid="katex-error">
        {latex}
      </code>
    )
  }

  const Tag = display ? 'div' : 'span'
  return (
    <Tag
      data-testid={display ? 'katex-block' : 'katex-inline'}
      className={display ? 'katex-display-wrapper' : 'katex-inline-wrapper'}
      // oxlint-disable-next-line react/no-danger -- KaTeX output is generated by
      // katex.renderToString from LaTeX source (no HTML passthrough); it is the
      // library's own sanitized markup, mirroring MermaidDiagram's SVG injection.
      dangerouslySetInnerHTML={{ __html: html }}
    />
  )
}
