/**
 * PairingDialog -- modal dialog for device pairing (#219).
 *
 * Three sections:
 *  1. QR code + passphrase display (generated by startPairing)
 *  2. Passphrase entry (4 word inputs) for joining from another device
 *  3. List of already-paired devices with Unpair action
 *
 * Props: open (boolean), onOpenChange (callback), triggerRef (optional).
 */

import { Camera, Loader2, Smartphone, X } from 'lucide-react'
import type React from 'react'
import { lazy, Suspense, useCallback, useEffect, useRef, useState } from 'react'
import { useTranslation } from 'react-i18next'
import { toast } from 'sonner'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Separator } from '@/components/ui/separator'
import { formatLastSynced } from '@/lib/format'
import type { PeerRefRow } from '../lib/tauri'
import {
  cancelPairing,
  confirmPairing,
  deletePeerRef,
  listPeerRefs,
  startPairing,
} from '../lib/tauri'
import { useSyncStore } from '../stores/sync'
import { UnpairConfirmDialog } from './UnpairConfirmDialog'

// Lazy-load QrScanner to avoid bundling html5-qrcode on desktop
const LazyQrScanner = lazy(() => import('./QrScanner').then((m) => ({ default: m.QrScanner })))

interface PairingDialogProps {
  open: boolean
  onOpenChange: (open: boolean) => void
  triggerRef?: React.RefObject<HTMLButtonElement | null>
}

const PAIRING_TIMEOUT_SECONDS = 300 // 5 minutes

export function PairingDialog({
  open,
  onOpenChange,
  triggerRef,
}: PairingDialogProps): React.ReactElement | null {
  const [pairingInfo, setPairingInfo] = useState<{
    passphrase: string
    qr_svg: string
    port: number
  } | null>(null)
  const [words, setWords] = useState<[string, string, string, string]>(['', '', '', ''])
  const [peers, setPeers] = useState<PeerRefRow[]>([])
  const [loading, setLoading] = useState(false)
  const [pairLoading, setPairLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [unpairPeerId, setUnpairPeerId] = useState<string | null>(null)
  const [countdown, setCountdown] = useState<number | null>(null)
  const [entryMode, setEntryMode] = useState<'manual' | 'scan'>('manual')

  const { t } = useTranslation()
  const dialogRef = useRef<HTMLDivElement>(null)
  const retryBtnRef = useRef<HTMLButtonElement>(null)

  // Helper: query word inputs from the DOM (Input component doesn't forward refs)
  const getWordInputs = useCallback(
    () =>
      dialogRef.current
        ? Array.from(
            dialogRef.current.querySelectorAll<HTMLInputElement>('.pairing-word-inputs input'),
          )
        : [],
    [],
  )

  const syncSetState = useSyncStore((s) => s.setState)

  // init function extracted so it can be called for retry (#282)
  const init = useCallback(async () => {
    setLoading(true)
    setError(null)
    try {
      const [info, peerList] = await Promise.all([startPairing(), listPeerRefs()])
      setPairingInfo(info)
      setPeers(peerList)
      setCountdown(PAIRING_TIMEOUT_SECONDS)
    } catch (err) {
      console.error('Failed to initialize pairing:', err)
      setError(`Failed to start pairing: ${String(err instanceof Error ? err.message : err)}`)
    }
    setLoading(false)
  }, [])

  // Load pairing info and peer list when dialog opens;
  // cancel the pairing session on close/unmount to avoid leaking the listener.
  useEffect(() => {
    if (!open) return

    let cancelled = false

    async function doInit() {
      await init()
    }

    doInit().then(() => {
      if (cancelled) {
        // Component closed before init finished — clean up
      }
    })

    return () => {
      cancelled = true
      // Cancel any in-progress pairing when the dialog closes or unmounts
      cancelPairing().catch(() => toast.error(t('pairing.cancelFailed')))
    }
  }, [open, init, t])

  // Countdown timer (#294) — only re-run effect when active/inactive changes
  const countdownActive = countdown !== null && countdown > 0
  useEffect(() => {
    if (!countdownActive) return

    const interval = setInterval(() => {
      setCountdown((prev) => {
        if (prev === null || prev <= 1) {
          clearInterval(interval)
          return 0
        }
        return prev - 1
      })
    }, 1000)

    return () => clearInterval(interval)
  }, [countdownActive])

  // Focus first word input when pairing info is loaded
  useEffect(() => {
    if (open && pairingInfo) {
      const inputs = getWordInputs()
      inputs[0]?.focus()
    }
  }, [open, pairingInfo, getWordInputs])

  // #279: Paste support — when pasting multi-word text, split and distribute across inputs
  const handleWordChange = useCallback(
    (index: number, value: string) => {
      const trimmed = value.trim().toLowerCase()
      const parts = trimmed.split(/\s+/)

      if (parts.length > 1) {
        // Paste detected: distribute words across inputs starting at index
        setWords((prev) => {
          const next = [...prev] as [string, string, string, string]
          for (let i = 0; i < parts.length && index + i < 4; i++) {
            next[index + i] = parts[i]
          }
          return next
        })
        // Focus the next empty input after the distributed words
        const nextEmpty = Math.min(index + parts.length, 3)
        setTimeout(() => {
          const inputs = getWordInputs()
          inputs[nextEmpty]?.focus()
        }, 0)
      } else {
        setWords((prev) => {
          const next = [...prev] as [string, string, string, string]
          next[index] = trimmed
          return next
        })
      }
    },
    [getWordInputs],
  )

  const handlePair = useCallback(async () => {
    const passphrase = words.join(' ').trim()
    if (!passphrase || words.some((w) => w === '')) return

    setPairLoading(true)
    setError(null)
    try {
      // remoteDeviceId is derived from the passphrase in the pairing protocol
      await confirmPairing(passphrase, '')
      syncSetState('idle')
      // Refresh peer list
      const peerList = await listPeerRefs()
      setPeers(peerList)
      setWords(['', '', '', ''])
      toast.success(t('pairing.successMessage'))
      onOpenChange(false)
    } catch (err) {
      console.error('Pairing failed:', err)
      setError(`Pairing failed: ${String(err instanceof Error ? err.message : err)}`)
    }
    setPairLoading(false)
  }, [words, syncSetState, onOpenChange, t])

  // #279: Space auto-advance and Enter-to-submit (uses DOM queries for focus)
  const handleWordKeyDown = useCallback(
    (index: number, e: React.KeyboardEvent<HTMLInputElement>) => {
      if (e.key === ' ') {
        e.preventDefault()
        if (index < 3) {
          const inputs = getWordInputs()
          inputs[index + 1]?.focus()
        }
      } else if (e.key === 'Enter') {
        e.preventDefault()
        handlePair()
      }
    },
    [handlePair, getWordInputs],
  )

  // Handle QR scan result: parse passphrase and auto-fill word inputs
  const handleQrScan = useCallback(
    (data: string) => {
      // QR data may be JSON with a passphrase field or a plain passphrase string
      let passphrase = data
      try {
        const obj = JSON.parse(data)
        if (obj && typeof obj.passphrase === 'string') {
          passphrase = obj.passphrase
        }
      } catch {
        // Not JSON — use raw text as passphrase
      }

      const parts = passphrase.trim().toLowerCase().split(/\s+/)
      const newWords: [string, string, string, string] = [
        parts[0] ?? '',
        parts[1] ?? '',
        parts[2] ?? '',
        parts[3] ?? '',
      ]
      setWords(newWords)
      setEntryMode('manual') // Switch back so user can verify before confirming
      toast.success(t('pairing.qrScannedMessage'))
    },
    [t],
  )

  const handleCancel = useCallback(async () => {
    try {
      await cancelPairing()
    } catch (err) {
      console.error('Failed to cancel pairing:', err)
    }
    setPairingInfo(null)
    setWords(['', '', '', ''])
    setError(null)
    setCountdown(null)
    setEntryMode('manual')
    onOpenChange(false)
    // #288: Return focus to trigger element
    triggerRef?.current?.focus()
  }, [onOpenChange, triggerRef])

  const handleUnpair = useCallback(async (peerId: string) => {
    try {
      await deletePeerRef(peerId)
      setPeers((prev) => prev.filter((p) => p.peer_id !== peerId))
      setUnpairPeerId(null)
    } catch (err) {
      console.error('Failed to unpair device:', err)
      setError(`Failed to unpair device: ${String(err instanceof Error ? err.message : err)}`)
    }
  }, [])

  // Handle Escape key and focus trap
  useEffect(() => {
    if (!open) return

    function handleKeyDown(e: KeyboardEvent) {
      if (e.key === 'Escape') {
        handleCancel()
        return
      }

      // Focus trap: keep Tab within the dialog
      if (e.key === 'Tab' && dialogRef.current) {
        const focusable = dialogRef.current.querySelectorAll<HTMLElement>(
          'button:not([disabled]), input:not([disabled]), [tabindex]:not([tabindex="-1"])',
        )
        if (focusable.length === 0) return
        const first = focusable[0]
        const last = focusable[focusable.length - 1]

        if (e.shiftKey) {
          if (document.activeElement === first) {
            e.preventDefault()
            last.focus()
          }
        } else {
          if (document.activeElement === last) {
            e.preventDefault()
            first.focus()
          }
        }
      }
    }

    window.addEventListener('keydown', handleKeyDown)
    return () => window.removeEventListener('keydown', handleKeyDown)
  }, [open, handleCancel])

  // #294: Format countdown for display
  const isExpired = countdown !== null && countdown <= 0
  const countdownDisplay =
    countdown !== null && countdown > 0
      ? `${Math.floor(countdown / 60)}:${String(countdown % 60).padStart(2, '0')}`
      : null

  // #430: Move focus to Retry button when error or expiry occurs
  useEffect(() => {
    if ((error || isExpired) && retryBtnRef.current) {
      retryBtnRef.current.focus()
    }
  }, [error, isExpired])

  if (!open) return null

  return (
    <>
      <button
        type="button"
        className="pairing-dialog-overlay fixed inset-0 z-50 bg-black/50 dark:bg-black/60 border-none cursor-default"
        onClick={handleCancel}
        tabIndex={-1}
        aria-label={t('pairing.closeDialogLabel')}
      />
      <div
        ref={dialogRef}
        className="pairing-dialog fixed top-[50%] left-[50%] z-50 w-full max-w-[calc(100%-2rem)] translate-x-[-50%] translate-y-[-50%] rounded-lg border bg-background p-6 shadow-lg sm:max-w-lg"
        role="dialog"
        aria-labelledby="pairing-dialog-title"
        aria-modal="true"
      >
        {/* Header */}
        <div className="flex items-center justify-between mb-4">
          <h2 id="pairing-dialog-title" className="text-lg font-semibold">
            {t('pairing.dialogTitle')}
          </h2>
          <Button
            variant="ghost"
            size="sm"
            onClick={handleCancel}
            aria-label={t('pairing.closeDialogLabel')}
            className="[@media(pointer:coarse)]:min-h-[44px] [@media(pointer:coarse)]:min-w-[44px]"
          >
            <X className="h-4 w-4" />
          </Button>
        </div>

        {/* Error message with Retry button (#282) */}
        {error && (
          <div className="pairing-error flex items-center gap-2 mb-4" aria-live="polite">
            <p className="text-sm text-destructive flex-1">{error}</p>
            <Button
              variant="outline"
              size="sm"
              ref={retryBtnRef}
              onClick={() => init()}
              className="pairing-retry-btn shrink-0"
            >
              Retry
            </Button>
          </div>
        )}

        {/* Loading state */}
        {loading && (
          <div className="pairing-loading flex items-center justify-center py-8">
            <Loader2 className="h-4 w-4 animate-spin text-muted-foreground" />
            <span className="ml-2 text-sm text-muted-foreground">
              {t('pairing.startingMessage')}
            </span>
          </div>
        )}

        {/* QR + Passphrase display */}
        {!loading && pairingInfo && (
          <>
            <div className="flex flex-col sm:flex-row [@media(pointer:coarse)]:flex-col gap-4 items-center mb-4">
              {/* #290: Use backend QR SVG instead of react-qr-code */}
              <div
                className="pairing-qr shrink-0 max-w-full rounded-lg border bg-white p-3"
                role="img"
                aria-label={t('pairing.qrCodeLabel')}
                data-testid="pairing-qr-code"
                // biome-ignore lint/security/noDangerouslySetInnerHtml: SVG from our own Rust backend, not user input
                dangerouslySetInnerHTML={{ __html: pairingInfo.qr_svg }}
              />
              <div className="flex flex-col gap-1">
                <span className="text-sm font-medium text-muted-foreground">
                  {t('pairing.passphraseLabel')}
                </span>
                <p className="pairing-passphrase text-lg font-mono font-semibold">
                  {pairingInfo.passphrase}
                </p>
                <p className="text-xs text-muted-foreground mt-1">
                  {t('pairing.scanOrEnterInstruction')}
                </p>
                {/* #294: Countdown timer */}
                {countdownDisplay && (
                  <p
                    className="pairing-countdown text-xs text-muted-foreground mt-1"
                    aria-hidden="true"
                  >
                    {t('pairing.sessionExpiresIn')} {countdownDisplay}
                  </p>
                )}
                {/* #424: SR-only countdown — announces at key intervals only */}
                <p className="sr-only" aria-live="polite" aria-atomic="true">
                  {countdown !== null && countdown > 0 && (countdown % 60 === 0 || countdown === 30)
                    ? `Session expires in ${
                        countdown >= 60
                          ? `${Math.floor(countdown / 60)} minute${
                              Math.floor(countdown / 60) !== 1 ? 's' : ''
                            }`
                          : `${countdown} seconds`
                      }`
                    : ''}
                </p>
                {isExpired && !error && (
                  <div className="pairing-expired flex items-center gap-2 mt-1">
                    <p className="text-xs text-destructive font-medium flex-1">
                      {t('pairing.sessionExpired')}
                    </p>
                    <Button
                      variant="outline"
                      size="sm"
                      ref={retryBtnRef}
                      onClick={() => init()}
                      className="pairing-retry-expired-btn shrink-0"
                    >
                      {t('pairing.retryButton')}
                    </Button>
                  </div>
                )}
              </div>
            </div>

            <div className="relative my-4">
              <Separator />
              <span className="pairing-separator absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2 bg-background px-2 text-xs text-muted-foreground">
                {t('pairing.orSeparator')}
              </span>
            </div>

            {/* Entry mode toggle: manual passphrase vs QR scan */}
            <div className="pairing-entry-toggle flex gap-2 mb-4 justify-center">
              <Button
                variant={entryMode === 'manual' ? 'default' : 'outline'}
                size="sm"
                onClick={() => setEntryMode('manual')}
                className="[@media(pointer:coarse)]:min-h-[44px]"
              >
                {t('pairing.typePassphraseButton')}
              </Button>
              <Button
                variant={entryMode === 'scan' ? 'default' : 'outline'}
                size="sm"
                onClick={() => setEntryMode('scan')}
                className="[@media(pointer:coarse)]:min-h-[44px]"
              >
                <Camera className="h-4 w-4 mr-1" />
                {t('pairing.scanQrCodeButton')}
              </Button>
            </div>

            {/* Conditional: manual word inputs or QR scanner */}
            {entryMode === 'manual' ? (
              <div className="pairing-word-inputs grid grid-cols-2 sm:grid-cols-4 gap-2 mb-4">
                {(['first', 'second', 'third', 'fourth'] as const).map((slot, i) => (
                  <Input
                    key={slot}
                    value={words[i]}
                    onChange={(e) => handleWordChange(i, e.target.value)}
                    onKeyDown={(e) => handleWordKeyDown(i, e)}
                    placeholder={t('pairing.wordPlaceholder', {
                      ordinal: ['1st', '2nd', '3rd', '4th'][i],
                    })}
                    aria-label={t('pairing.wordLabel', { num: i + 1 })}
                    className="text-center [@media(pointer:coarse)]:min-h-[44px]"
                    disabled={pairLoading || isExpired}
                  />
                ))}
              </div>
            ) : (
              <div className="pairing-qr-scanner mb-4">
                <Suspense
                  fallback={
                    <div className="flex items-center justify-center py-8">
                      <Loader2 className="h-4 w-4 animate-spin text-muted-foreground" />
                      <span className="ml-2 text-sm text-muted-foreground">
                        {t('pairing.loadingScannerMessage')}
                      </span>
                    </div>
                  }
                >
                  <LazyQrScanner
                    onScan={handleQrScan}
                    onError={(err) => setError(`Camera error: ${err}`)}
                  />
                </Suspense>
              </div>
            )}

            {/* Action buttons */}
            <div className="flex justify-between gap-2 mb-4">
              <Button
                variant="outline"
                onClick={handleCancel}
                disabled={pairLoading}
                className="[@media(pointer:coarse)]:min-h-[44px]"
              >
                {t('pairing.cancelButton')}
              </Button>
              <Button
                onClick={handlePair}
                disabled={pairLoading || words.some((w) => w === '') || isExpired}
                className="pairing-pair-btn [@media(pointer:coarse)]:min-h-[44px]"
              >
                {pairLoading && <Loader2 className="h-4 w-4 animate-spin mr-1" />}
                {t('pairing.pairButton')}
              </Button>
            </div>
          </>
        )}

        {/* Paired Devices */}
        {!loading && (
          <>
            <Separator className="my-4" />
            <div className="pairing-peers">
              <h3 className="text-sm font-medium mb-2">{t('pairing.pairedDevicesTitle')}</h3>
              {peers.length === 0 ? (
                <p className="text-sm text-muted-foreground">{t('pairing.noPairedDevices')}</p>
              ) : (
                <div className="space-y-2">
                  {peers.map((peer) => (
                    <Card key={peer.peer_id} className="pairing-peer-item p-3">
                      <div className="flex items-center justify-between">
                        <div className="flex items-center gap-2 min-w-0">
                          <Smartphone className="h-4 w-4 shrink-0 text-muted-foreground" />
                          <div className="min-w-0">
                            <p className="text-sm font-mono truncate">{peer.peer_id}</p>
                            <p className="text-xs text-muted-foreground">
                              Last: {formatLastSynced(peer.synced_at)}
                            </p>
                            {peer.reset_count > 0 && (
                              <Badge variant="outline" className="mt-0.5 text-xs">
                                {peer.reset_count} reset{peer.reset_count !== 1 ? 's' : ''}
                              </Badge>
                            )}
                          </div>
                        </div>
                        <Button
                          variant="destructive"
                          size="sm"
                          onClick={() => setUnpairPeerId(peer.peer_id)}
                          className="pairing-unpair-btn shrink-0 [@media(pointer:coarse)]:min-h-[44px]"
                        >
                          Unpair
                        </Button>
                      </div>
                    </Card>
                  ))}
                </div>
              )}
            </div>
          </>
        )}

        {/* Status message for screen readers */}
        <div aria-live="polite" className="sr-only">
          {loading && t('pairing.startingMessage')}
          {pairLoading && 'Pairing in progress...'}
          {error}
        </div>
      </div>

      {/* #301: Use shared UnpairConfirmDialog */}
      <UnpairConfirmDialog
        open={!!unpairPeerId}
        onOpenChange={(o) => {
          if (!o) setUnpairPeerId(null)
        }}
        onConfirm={() => {
          if (unpairPeerId) handleUnpair(unpairPeerId)
        }}
        className="pairing-unpair-confirm"
      />
    </>
  )
}
