/**
 * PairingDialog -- modal dialog for device pairing (#219).
 *
 * Three sections:
 *  1. QR code + passphrase display (generated by startPairing)
 *  2. Passphrase entry (4 word inputs) for joining from another device
 *  3. List of already-paired devices with Unpair action
 *
 * Props: open (boolean), onOpenChange (callback).
 */

import { Loader2, Smartphone, X } from 'lucide-react'
import type React from 'react'
import { useCallback, useEffect, useRef, useState } from 'react'
import QRCode from 'react-qr-code'
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from '@/components/ui/alert-dialog'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Separator } from '@/components/ui/separator'
import type { PeerRefRow } from '../lib/tauri'
import {
  cancelPairing,
  confirmPairing,
  deletePeerRef,
  listPeerRefs,
  startPairing,
} from '../lib/tauri'
import { useSyncStore } from '../stores/sync'

interface PairingDialogProps {
  open: boolean
  onOpenChange: (open: boolean) => void
}

export function PairingDialog({
  open,
  onOpenChange,
}: PairingDialogProps): React.ReactElement | null {
  const [pairingInfo, setPairingInfo] = useState<{
    passphrase: string
    qr_svg: string
    port: number
  } | null>(null)
  const [words, setWords] = useState<[string, string, string, string]>(['', '', '', ''])
  const [peers, setPeers] = useState<PeerRefRow[]>([])
  const [loading, setLoading] = useState(false)
  const [pairLoading, setPairLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [unpairPeerId, setUnpairPeerId] = useState<string | null>(null)

  const firstInputRef = useRef<HTMLInputElement>(null)
  const dialogRef = useRef<HTMLDivElement>(null)

  const syncSetState = useSyncStore((s) => s.setState)

  // Load pairing info and peer list when dialog opens;
  // cancel the pairing session on close/unmount to avoid leaking the listener.
  useEffect(() => {
    if (!open) return

    let cancelled = false

    async function init() {
      setLoading(true)
      setError(null)
      try {
        const [info, peerList] = await Promise.all([startPairing(), listPeerRefs()])
        if (cancelled) return
        setPairingInfo(info)
        setPeers(peerList)
      } catch (err) {
        if (cancelled) return
        console.error('Failed to initialize pairing:', err)
        setError('Failed to start pairing. Please try again.')
      }
      if (!cancelled) setLoading(false)
    }

    init()

    return () => {
      cancelled = true
      // Cancel any in-progress pairing when the dialog closes or unmounts
      cancelPairing().catch(() => {})
    }
  }, [open])

  // Focus first word input when pairing info is loaded
  useEffect(() => {
    if (open && pairingInfo && firstInputRef.current) {
      firstInputRef.current.focus()
    }
  }, [open, pairingInfo])

  const handleWordChange = useCallback((index: number, value: string) => {
    setWords((prev) => {
      const next = [...prev] as [string, string, string, string]
      next[index] = value.trim().toLowerCase()
      return next
    })
  }, [])

  const handlePair = useCallback(async () => {
    const passphrase = words.join(' ').trim()
    if (!passphrase || words.some((w) => w === '')) return

    setPairLoading(true)
    setError(null)
    try {
      // remoteDeviceId is derived from the passphrase in the pairing protocol
      await confirmPairing(passphrase, '')
      syncSetState('idle')
      // Refresh peer list
      const peerList = await listPeerRefs()
      setPeers(peerList)
      setWords(['', '', '', ''])
    } catch (err) {
      console.error('Pairing failed:', err)
      setError('Pairing failed. Check the passphrase and try again.')
    }
    setPairLoading(false)
  }, [words, syncSetState])

  const handleCancel = useCallback(async () => {
    try {
      await cancelPairing()
    } catch (err) {
      console.error('Failed to cancel pairing:', err)
    }
    setPairingInfo(null)
    setWords(['', '', '', ''])
    setError(null)
    onOpenChange(false)
  }, [onOpenChange])

  const handleUnpair = useCallback(async (peerId: string) => {
    try {
      await deletePeerRef(peerId)
      setPeers((prev) => prev.filter((p) => p.peer_id !== peerId))
      setUnpairPeerId(null)
    } catch (err) {
      console.error('Failed to unpair device:', err)
      setError('Failed to unpair device.')
    }
  }, [])

  // Handle Escape key and focus trap
  useEffect(() => {
    if (!open) return

    function handleKeyDown(e: KeyboardEvent) {
      if (e.key === 'Escape') {
        handleCancel()
        return
      }

      // Focus trap: keep Tab within the dialog
      if (e.key === 'Tab' && dialogRef.current) {
        const focusable = dialogRef.current.querySelectorAll<HTMLElement>(
          'button:not([disabled]), input:not([disabled]), [tabindex]:not([tabindex="-1"])',
        )
        if (focusable.length === 0) return
        const first = focusable[0]
        const last = focusable[focusable.length - 1]

        if (e.shiftKey) {
          if (document.activeElement === first) {
            e.preventDefault()
            last.focus()
          }
        } else {
          if (document.activeElement === last) {
            e.preventDefault()
            first.focus()
          }
        }
      }
    }

    window.addEventListener('keydown', handleKeyDown)
    return () => window.removeEventListener('keydown', handleKeyDown)
  }, [open, handleCancel])

  function formatLastSynced(syncedAt: string | null): string {
    if (!syncedAt) return 'Never synced'
    try {
      const date = new Date(syncedAt)
      const now = new Date()
      const diffMs = now.getTime() - date.getTime()
      const diffMin = Math.floor(diffMs / 60000)
      if (diffMin < 1) return 'Just now'
      if (diffMin < 60) return `${diffMin} min ago`
      const diffHours = Math.floor(diffMin / 60)
      if (diffHours < 24) return `${diffHours}h ago`
      const diffDays = Math.floor(diffHours / 24)
      return `${diffDays}d ago`
    } catch {
      return syncedAt
    }
  }

  if (!open) return null

  return (
    <>
      <button
        type="button"
        className="pairing-dialog-overlay fixed inset-0 z-50 bg-black/50 dark:bg-black/60 border-none cursor-default"
        onClick={handleCancel}
        tabIndex={-1}
        aria-label="Close pairing dialog"
      />
      <div
        ref={dialogRef}
        className="pairing-dialog fixed top-[50%] left-[50%] z-50 w-full max-w-[calc(100%-2rem)] translate-x-[-50%] translate-y-[-50%] rounded-lg border bg-background p-6 shadow-lg sm:max-w-lg"
        role="dialog"
        aria-labelledby="pairing-dialog-title"
        aria-modal="true"
      >
        {/* Header */}
        <div className="flex items-center justify-between mb-4">
          <h2 id="pairing-dialog-title" className="text-lg font-semibold">
            Pair Device
          </h2>
          <Button
            variant="ghost"
            size="sm"
            onClick={handleCancel}
            aria-label="Close pairing dialog"
            className="[@media(pointer:coarse)]:min-h-[44px] [@media(pointer:coarse)]:min-w-[44px]"
          >
            <X className="h-4 w-4" />
          </Button>
        </div>

        {/* Error message */}
        {error && (
          <p className="pairing-error text-sm text-destructive mb-4" aria-live="polite">
            {error}
          </p>
        )}

        {/* Loading state */}
        {loading && (
          <div className="pairing-loading flex items-center justify-center py-8">
            <Loader2 className="h-6 w-6 animate-spin text-muted-foreground" />
            <span className="ml-2 text-sm text-muted-foreground">Starting pairing...</span>
          </div>
        )}

        {/* QR + Passphrase display */}
        {!loading && pairingInfo && (
          <>
            <div className="flex flex-col sm:flex-row gap-4 items-center mb-4">
              <div
                className="pairing-qr shrink-0 rounded-lg border bg-white p-3"
                role="img"
                aria-label="QR code for device pairing"
              >
                <QRCode value={pairingInfo.passphrase} size={128} data-testid="pairing-qr-code" />
              </div>
              <div className="flex flex-col gap-1">
                <span className="text-sm font-medium text-muted-foreground">Passphrase:</span>
                <p className="pairing-passphrase text-lg font-mono font-semibold">
                  {pairingInfo.passphrase}
                </p>
                <p className="text-xs text-muted-foreground mt-1">
                  Scan the QR code or enter the passphrase on the other device.
                </p>
              </div>
            </div>

            <div className="relative my-4">
              <Separator />
              <span className="pairing-separator absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2 bg-background px-2 text-xs text-muted-foreground">
                OR enter passphrase
              </span>
            </div>

            {/* Word inputs */}
            <div className="pairing-word-inputs grid grid-cols-4 gap-2 mb-4">
              {(['first', 'second', 'third', 'fourth'] as const).map((slot, i) => (
                <Input
                  key={slot}
                  ref={i === 0 ? firstInputRef : undefined}
                  value={words[i]}
                  onChange={(e) => handleWordChange(i, e.target.value)}
                  placeholder={`word ${i + 1}`}
                  aria-label={`Passphrase word ${i + 1}`}
                  className="text-center [@media(pointer:coarse)]:min-h-[44px]"
                  disabled={pairLoading}
                />
              ))}
            </div>

            {/* Action buttons */}
            <div className="flex justify-between gap-2 mb-4">
              <Button
                variant="outline"
                onClick={handleCancel}
                disabled={pairLoading}
                className="[@media(pointer:coarse)]:min-h-[44px]"
              >
                Cancel
              </Button>
              <Button
                onClick={handlePair}
                disabled={pairLoading || words.some((w) => w === '')}
                className="pairing-pair-btn [@media(pointer:coarse)]:min-h-[44px]"
              >
                {pairLoading && <Loader2 className="h-4 w-4 animate-spin mr-1" />}
                Pair
              </Button>
            </div>
          </>
        )}

        {/* Paired Devices */}
        {!loading && (
          <>
            <Separator className="my-4" />
            <div className="pairing-peers">
              <h3 className="text-sm font-medium mb-2">Paired Devices</h3>
              {peers.length === 0 ? (
                <p className="text-sm text-muted-foreground">No paired devices yet.</p>
              ) : (
                <div className="space-y-2">
                  {peers.map((peer) => (
                    <Card key={peer.peer_id} className="pairing-peer-item p-3">
                      <div className="flex items-center justify-between">
                        <div className="flex items-center gap-2 min-w-0">
                          <Smartphone className="h-4 w-4 shrink-0 text-muted-foreground" />
                          <div className="min-w-0">
                            <p className="text-sm font-mono truncate">{peer.peer_id}</p>
                            <p className="text-xs text-muted-foreground">
                              Last: {formatLastSynced(peer.synced_at)}
                            </p>
                            {peer.reset_count > 0 && (
                              <Badge variant="outline" className="mt-0.5 text-xs">
                                {peer.reset_count} reset{peer.reset_count !== 1 ? 's' : ''}
                              </Badge>
                            )}
                          </div>
                        </div>
                        <Button
                          variant="destructive"
                          size="sm"
                          onClick={() => setUnpairPeerId(peer.peer_id)}
                          className="pairing-unpair-btn shrink-0 [@media(pointer:coarse)]:min-h-[44px]"
                        >
                          Unpair
                        </Button>
                      </div>
                    </Card>
                  ))}
                </div>
              )}
            </div>
          </>
        )}

        {/* Status message for screen readers */}
        <div aria-live="polite" className="sr-only">
          {loading && 'Starting pairing...'}
          {pairLoading && 'Pairing in progress...'}
          {error}
        </div>
      </div>

      {/* Unpair confirmation dialog */}
      <AlertDialog
        open={!!unpairPeerId}
        onOpenChange={(dialogOpen) => {
          if (!dialogOpen) setUnpairPeerId(null)
        }}
      >
        <AlertDialogContent className="pairing-unpair-confirm">
          <AlertDialogHeader>
            <AlertDialogTitle>Unpair device?</AlertDialogTitle>
            <AlertDialogDescription>
              This will remove the paired device. You will need to pair again to sync.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>Cancel</AlertDialogCancel>
            <AlertDialogAction
              className="pairing-unpair-yes"
              onClick={() => {
                if (unpairPeerId) handleUnpair(unpairPeerId)
              }}
            >
              Yes, unpair
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </>
  )
}
