/**
 * MAINT-123 — runtime mock-drift detection.
 *
 * `HANDLERS` in `../handlers.ts` is typed as `Record<string, Handler>`, which
 * means TypeScript can't catch when a new Tauri command is added to
 * `src/lib/bindings.ts` (auto-generated by Tauri Specta) without a matching
 * mock entry. Until we land a full type-level link between the two files
 * (non-trivial because `bindings.ts` is `// @ts-nocheck` auto-gen), this test
 * provides the runtime safety net.
 *
 * Approach: read `bindings.ts` source as text and regex-extract every
 * `__TAURI_INVOKE("snake_case_name", ...)` literal. Each extracted name must
 * either appear as a key in `HANDLERS` or be on the `INTENTIONALLY_NOT_MOCKED`
 * allowlist below.
 *
 * We deliberately avoid the camelCase→snake_case conversion approach: acronyms
 * (`gcal`, `mcp`, `id`) and other edge cases mean the mapping isn't 1:1, and
 * regexing the literal strings the backend actually receives is exact.
 */

import { readFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

import { describe, expect, it } from 'vitest'

import { HANDLERS } from '../handlers'

// ---------------------------------------------------------------------------
// Allowlist
// ---------------------------------------------------------------------------

/**
 * Commands deliberately NOT mocked. Empty today — every command in
 * `bindings.ts` has a handler. Add entries here (with a comment explaining
 * why) if a future command should be skipped, e.g. system-level Tauri APIs
 * that don't make sense to mock for browser-mode rendering.
 */
const INTENTIONALLY_NOT_MOCKED: ReadonlySet<string> = new Set<string>()

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

const BINDINGS_PATH = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  '..',
  '..',
  'bindings.ts',
)

/**
 * Extract every Tauri command name from the auto-generated `bindings.ts`.
 * Each command appears exactly once as `__TAURI_INVOKE("snake_case_name", …)`
 * inside an arrow-function body on the `commands` object.
 */
function extractBindingsCommandNames(): string[] {
  const source = readFileSync(BINDINGS_PATH, 'utf8')
  const re = /__TAURI_INVOKE\("([a-z][a-z0-9_]*)"/g
  const names = new Set<string>()
  for (const match of source.matchAll(re)) {
    names.add(match[1] as string)
  }
  return [...names].sort()
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe('tauri-mock HANDLERS drift detection (MAINT-123)', () => {
  const bindingsCommands = extractBindingsCommandNames()
  const handlerKeys = new Set(Object.keys(HANDLERS))

  it('extracts a non-trivial number of commands from bindings.ts', () => {
    // Sanity check — guards against the regex silently breaking and reporting
    // zero commands (which would make the drift assertion vacuously pass).
    expect(bindingsCommands.length).toBeGreaterThan(50)
  })

  it('every command in bindings.ts has a HANDLERS entry or is allowlisted', () => {
    const missing = bindingsCommands.filter(
      (cmd) => !handlerKeys.has(cmd) && !INTENTIONALLY_NOT_MOCKED.has(cmd),
    )

    // Surface the full list in the failure message so the fix is obvious.
    expect(
      missing,
      `The following Tauri commands are exposed in src/lib/bindings.ts but ` +
        `have no entry in HANDLERS (and are not on INTENTIONALLY_NOT_MOCKED): ` +
        `${JSON.stringify(missing)}. Add a handler in ` +
        `src/lib/tauri-mock/handlers.ts or, if intentional, allowlist with a ` +
        `justification comment.`,
    ).toEqual([])
  })

  it('every HANDLERS key corresponds to a real command in bindings.ts', () => {
    // Reverse direction: a stale handler for a removed command is also drift.
    const stale = [...handlerKeys].filter(
      (cmd) => !bindingsCommands.includes(cmd) && !INTENTIONALLY_NOT_MOCKED.has(cmd),
    )
    expect(
      stale,
      `The following HANDLERS keys do not match any command in ` +
        `src/lib/bindings.ts: ${JSON.stringify(stale)}. Remove the stale ` +
        `handler or update the command name.`,
    ).toEqual([])
  })

  it('allowlisted commands are not also handled (avoid contradictory state)', () => {
    const contradictory = [...INTENTIONALLY_NOT_MOCKED].filter((cmd) => handlerKeys.has(cmd))
    expect(contradictory, 'Allowlisted commands must not also appear in HANDLERS.').toEqual([])
  })
})
